name: CI/CD Pipeline - Airbnb Clone

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

env:
  AZURE_RESOURCE_GROUP: airbnb-clone-rg
  AKS_CLUSTER_NAME: airbnb-clone-aks
  ACR_NAME: airbnbcloneacr
  NAMESPACE: airbnb-clone

jobs:
  # Job 1: Build and Test
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          airbnb-clone/api/package-lock.json
          airbnb-clone/client/package-lock.json
    
    - name: Install API dependencies
      working-directory: airbnb-clone/api
      run: npm ci
    
    - name: Install Client dependencies
      working-directory: airbnb-clone/client
      run: npm ci
    
    - name: Lint API code
      working-directory: airbnb-clone/api
      run: npm run lint --if-present
      continue-on-error: true
    
    - name: Lint Client code
      working-directory: airbnb-clone/client
      run: npm run lint --if-present
      continue-on-error: true
    
    - name: Run API tests
      working-directory: airbnb-clone/api
      run: npm test --if-present
      continue-on-error: true
    
    - name: Run Client tests
      working-directory: airbnb-clone/client
      run: npm test --if-present
      continue-on-error: true

  # Job 2: Build and Push Docker Images
  build-docker-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Login to Azure Container Registry
      run: |
        az acr login --name ${{ env.ACR_NAME }}
    
    - name: Set image tags
      id: tags
      run: |
        echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
        echo "DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
    
    - name: Build and Push API Image
      working-directory: airbnb-clone/api
      run: |
        docker build \
          --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
          --build-arg VCS_REF=${{ github.sha }} \
          -t ${{ env.ACR_NAME }}.azurecr.io/airbnb-api:${{ steps.tags.outputs.SHORT_SHA }} \
          -t ${{ env.ACR_NAME }}.azurecr.io/airbnb-api:${{ steps.tags.outputs.DATE }} \
          -t ${{ env.ACR_NAME }}.azurecr.io/airbnb-api:latest \
          .
        docker push ${{ env.ACR_NAME }}.azurecr.io/airbnb-api:${{ steps.tags.outputs.SHORT_SHA }}
        docker push ${{ env.ACR_NAME }}.azurecr.io/airbnb-api:${{ steps.tags.outputs.DATE }}
        docker push ${{ env.ACR_NAME }}.azurecr.io/airbnb-api:latest
    
    - name: Build and Push Client Image
      working-directory: airbnb-clone/client
      run: |
        docker build \
          --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
          --build-arg VCS_REF=${{ github.sha }} \
          -t ${{ env.ACR_NAME }}.azurecr.io/airbnb-client:${{ steps.tags.outputs.SHORT_SHA }} \
          -t ${{ env.ACR_NAME }}.azurecr.io/airbnb-client:${{ steps.tags.outputs.DATE }} \
          -t ${{ env.ACR_NAME }}.azurecr.io/airbnb-client:latest \
          .
        docker push ${{ env.ACR_NAME }}.azurecr.io/airbnb-client:${{ steps.tags.outputs.SHORT_SHA }}
        docker push ${{ env.ACR_NAME }}.azurecr.io/airbnb-client:${{ steps.tags.outputs.DATE }}
        docker push ${{ env.ACR_NAME }}.azurecr.io/airbnb-client:latest
    
    - name: Image scan (optional)
      run: |
        echo "Consider adding image scanning with Trivy or similar tools"
      continue-on-error: true

  # Job 3: Deploy to AKS
  deploy-to-aks:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    needs: build-docker-images
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: production
      url: ${{ steps.get-url.outputs.url }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Get AKS Credentials
      run: |
        az aks get-credentials \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name ${{ env.AKS_CLUSTER_NAME }} \
          --overwrite-existing
    
    - name: Set image tags
      id: tags
      run: |
        echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
    
    - name: Update Kubernetes manifests
      run: |
        # Create temporary directory for modified manifests
        mkdir -p /tmp/k8s
        cp airbnb-clone/k8s/*.yaml /tmp/k8s/
        
        # Update ACR name
        sed -i "s|REPLACE_WITH_ACR_NAME|${{ env.ACR_NAME }}|g" /tmp/k8s/*.yaml
        
        # Update image tags with commit SHA
        sed -i "s|:latest|:${{ steps.tags.outputs.SHORT_SHA }}|g" /tmp/k8s/api-deployment.yaml
        sed -i "s|:latest|:${{ steps.tags.outputs.SHORT_SHA }}|g" /tmp/k8s/client-deployment.yaml
    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f /tmp/k8s/namespace.yaml
        kubectl apply -f /tmp/k8s/secrets.yaml
        kubectl apply -f /tmp/k8s/configmap.yaml
        kubectl apply -f /tmp/k8s/api-deployment.yaml
        kubectl apply -f /tmp/k8s/client-deployment.yaml
    
    - name: Wait for deployment
      run: |
        kubectl wait --for=condition=available --timeout=300s \
          deployment/airbnb-api -n ${{ env.NAMESPACE }} || \
          (kubectl describe deployment airbnb-api -n ${{ env.NAMESPACE }} && exit 1)
        
        kubectl wait --for=condition=available --timeout=300s \
          deployment/airbnb-client -n ${{ env.NAMESPACE }} || \
          (kubectl describe deployment airbnb-client -n ${{ env.NAMESPACE }} && exit 1)
    
    - name: Get Service URLs
      id: get-url
      run: |
        echo "Deployment successful!"
        kubectl get svc -n ${{ env.NAMESPACE }}
        
        # Get LoadBalancer IP
        LB_IP=$(kubectl get svc airbnb-client-service -n ${{ env.NAMESPACE }} \
          -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        
        echo "Application URL: http://${LB_IP}"
        echo "url=http://${LB_IP}" >> $GITHUB_OUTPUT
    
    - name: Deployment summary
      run: |
        echo "### Deployment Summary :rocket:" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Image Tag**: ${{ steps.tags.outputs.SHORT_SHA }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Application URL**: ${{ steps.get-url.outputs.url }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "#### Deployed Pods" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        kubectl get pods -n ${{ env.NAMESPACE }} >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
    
    - name: Notify on failure
      if: failure()
      run: |
        echo "### Deployment Failed :x:" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Check the logs above for details" >> $GITHUB_STEP_SUMMARY
